version: '2'
services:
  nginx:
   image: nginx
   volumes:
     - ./src:/var/www/html
     - ./src/docker-conf/site.conf:/etc/nginx/conf.d/default.conf
   ports:
     - 8888:80
   links:
     - vokuro:php
  vokuro:
    build:
     context: ./src
    volumes:
      - ./src:/var/www/html
    links:
      - mysql:mysql
    depends_on:
      - mysql
      
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_12345
      - MYSQL_DATABASE=vokuro
    volumes:
      - ./stack/mysql/data:/var/lib/mysql:rw
      - ./stack/mysql/entrypoint:/docker-entrypoint-initdb.d
